### ISSUE TITLE
create-react-app 运行 npm start 报错？

### ISSUE THREAD

**Issue by happypeter** [happypeter/dj-demos#2]
![2017-09-07 9 23 03](https://user-images.githubusercontent.com/72467/30141469-355ef172-93ae-11e7-8dc4-711018934ce8.png)

### 如何复现

```
create-react-app project
cd project
npm i
cd ..
cp -rf project new-project
```

然后，进入 new-project 项目，运行 npm start 就报出上面的错误了。

错误全文如下：

```
➜  peter-new git:(master) ✗ npm start

> props-demo@0.1.0 start /Users/peter/Desktop/dj-stuff/dj-demos/peter-new
> react-scripts start

module.js:491
    throw err;
    ^

Error: Cannot find module '../scripts/start'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Users/peter/Desktop/dj-stuff/dj-demos/peter-new/node_modules/.bin/react-scripts:30:25)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! props-demo@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the props-demo@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peter/.npm/_logs/2017-09-07T01_22_49_145Z-debug.log
```

**Comment by happypeter** [comment]
### 回答

上面的问题，就是由于对已有 create-react-app 项目重命名造成的


### 解决

```
cd new-project
rm -rf node_modules
npm i
```

这样，再去执行 `npm start` 就不会报错了。
